name: Cypress Tests

on: 
  pull_request:
    branches: '**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: build Dotnet
        - uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '6.0'
        - run: dotnet build
          working-directory: ./server
        - uses: actions/setup-node@v1
          with:
            working-directory: ./client
            node-version: 16
        - run: npm ci
        - uses: cypress-io/github-action@v4.2.2
          with:
            working-directory: ./client
            start: npm run cypress-tests
