name: Cypress Tests

on: 
  pull_request:
    branches: '**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
    steps:
    
        - uses: actions/checkout@v3
        - uses: actions/setup-dotnet@v3
          with:
            working-directory: ./server
            dotnet-version: '6.2.3'
        - run: dotnet build <my project>
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            working-directory: ./client
            node-version: 16
        - run: npm ci
        - uses: cypress-io/github-action@v4.2.2
          with:
            working-directory: ./client
            start: npm run cypress-tests